In [4]:
import pandas as pd
import numpy as np
import requests

In [25]:
def subjectTally(subjects,outputLabels):
    for i in subjects:
        print(i)
        if( i == "Physics"):
            outputLabels[0] += 6
            outputLabels[1] += 4
        if( i == "Chemistry"):
            outputLabels[0] += 3
            outputLabels[1] += 5
        if( i == "Mathematics"):
            outputLabels[0] += 7
            outputLabels[4] += 4
            outputLabels[3] += 2
        if( i == "Business Studies"):
            outputLabels[4] += 5
            outputLabels[3] += 5
        if( i == "Literature"):
            outputLabels[2] += 6
            outputLabels[3] += 2
        if( i == "Accountancy"):
            outputLabels[4] += 6
            outputLabels[3] += 5
        if( i == "Biology"):
            outputLabels[1] += 10
            outputLabels[0] += 1
        if( i == "Computer Science"):
            outputLabels[0] += 7
        if( i == "Economics"):
            outputLabels[2] += 4
            outputLabels[3] += 6
            outputLabels[4] += 6
        if( i == "Psychology"):
            outputLabels[2] += 6
        if( i == "History"):
            outputLabels[2] += 6
        if( i == "Geography"):
            outputLabels[2] += 6
        if( i == "Political Science (Civics)"):
            outputLabels[2] += 6

    return outputLabels

In [ ]:
def getOptionsfromStrings(str):
    l = str.split(', ')
    return l

In [30]:
def acadInclineTally(acads,outputLabels):
    outputLabels[0] += acads*4
    outputLabels[1] += acads*4.5
    outputLabels[2] += acads*1
    outputLabels[3] += acads*1.5
    outputLabels[4] += acads*2.5

    return outputLabels

In [5]:
data = pd.read_csv("userResponse.csv")
data

,Timestamp,Name,What are your favorite subjects?,How much do you like Academics,What suits your personality,How is your scope of interest,Choose from scale how inclined you are,Select your Board,MATHEMATICS (/100),SCIENCE (/100),ENGLISH (/100),HINDI (/100),SOCIAL STUDIES (/100)
0,7/21/2022 0:01:45,Siddhant Yadav,"Physics, Mathematics, Computer Science, Busine...",4,What suits your personality,Generalist (Like to know little about a lot of...,7,CBSE,99,96,90,97,98
1,7/22/2022 21:49:05,Kartik Anand,"Physics, Mathematics, Computer Science, Litera...",5,"Introvert, Patient, Hardworking",Specialist (Like to know a lot about a few thi...,2,CBSE,98,92,83,81,90
2,7/22/2022 21:50:22,Nishu,"Physics, Chemistry, Mathematics, Computer Science",3,"Introvert, Focused, Hardworking, Calculative",Generalist (Like to know little about a lot of...,1,CBSE,100,90,80,80,99

In [6]:
PCM = 0
PCB = 0
Humanities = 0
Commerce = 0
Commerce_w_maths = 0

outputLabels = [PCM,PCB,Humanities,Commerce,Commerce_w_maths]

In [29]:

# 
# outputLabels = [0,0,0,0,0]
# subjectTally(getOptionsfromStrings(data["What are your favorite subjects?"][0]),outputLabels)
# acadInclineTally(data["How much do you like Academics"][0],outputLabels)
#